version: '3'

services:
  flask-app:
    container_name: flask-app
    restart: always
    build: ./flask_app
    image: flask-app
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask-app